### ISSUE TITLE
Invalid certificates lead to crash of node-red

### ISSUE THREAD

**Issue by dkby** [iotblackbelt/node-red-contrib-azure-iot-device#8] opened 2020-12-22 14:05 UTC
Setting:
Using the node on Weidmueller u-controll web device (node red v1.1.2) . Provisioning with DPS (CA based x509).

When uploading invalid certificate files (we uploaded the csr file used for signing the client certificate as private key file), node red crashes.

![image](https://user-images.githubusercontent.com/76442931/102896692-12a42680-4467-11eb-82b3-ab0efceb1751.png)

**Comment by iotblackbelt** [comment] 2021-02-03 10:23
@dkby can you sent me a file to reproduce this error?

**Comment by dkby** [comment] 2021-02-08 09:58
When erroneously using a pfx file as private key (or certificate?), some time passes and then node-red crashes. I will put an example file below. This is the  node-red console log from our device:

Feb 04 13:32:48 ucg node[619]: 4 Feb 13:32:48 - [info] Starting flows
Feb 04 13:32:57 ucg node[619]: 4 Feb 13:32:57 - [info] [azureiotdevice:f97b180c.847ff8] DeviceForBugTest_1 -> Initiate IoT Device settings.
Feb 04 13:32:57 ucg node[619]: 4 Feb 13:32:57 - [info] [azureiotdevice:f97b180c.847ff8] DeviceForBugTest_1 -> Initiate IoT Device connection string.
Feb 04 13:32:58 ucg node[619]: 4 Feb 13:32:58 - [info] [azureiotdevice:f97b180c.847ff8] DeviceForBugTest_1 -> Provision IoT Device using DPS.
**Feb 04 13:32:58 ucg node[619]: 4 Feb 13:32:58 - [error] [azureiotdevice:f97b180c.847ff8] Error: error:0909006C:PEM routines:get_name:no start line**
Feb 04 13:32:58 ucg node[619]: 4 Feb 13:32:58 - [info] Started flows
Feb 04 13:33:28 ucg node[619]: 4 Feb 13:33:28 - [red] Uncaught Exception:
Feb 04 13:33:28 ucg node[619]: 4 Feb 13:33:28 - TypeError: Cannot read property 'removeAllListeners' of undefined
Feb 04 13:33:28 ucg node[619]:     at MqttBase._disconnectClient (/var/lib/node-red/node_modules/azure-iot-mqtt-base/dist/mqtt_base.js:474:26)
Feb 04 13:33:28 ucg node[619]:     at constructor._onEnter (/var/lib/node-red/node_modules/azure-iot-mqtt-base/dist/mqtt_base.js:286:31)
Feb 04 13:33:28 ucg node[619]:     at constructor.transition (/var/lib/node-red/node_modules/machina/lib/webpack:/src/BehavioralFsm.js:175:1)
Feb 04 13:33:28 ucg node[619]:     at constructor.Fsm.(anonymous function) [as transition] (/var/lib/node-red/node_modules/machina/lib/webpack:/src/Fsm.js:80:1)
Feb 04 13:33:28 ucg node[619]:     at constructor.disconnect (/var/lib/node-red/node_modules/azure-iot-mqtt-base/dist/mqtt_base.js:244:36)
Feb 04 13:33:28 ucg node[619]:     at constructor.handle (/var/lib/node-red/node_modules/machina/lib/webpack:/src/BehavioralFsm.js:135:1)
Feb 04 13:33:28 ucg node[619]:     at constructor.Fsm.(anonymous function) [as handle] (/var/lib/node-red/node_modules/machina/lib/webpack:/src/Fsm.js:80:1)
Feb 04 13:33:28 ucg node[619]:     at MqttBase.disconnect (/var/lib/node-red/node_modules/azure-iot-mqtt-base/dist/mqtt_base.js:362:19)
Feb 04 13:33:28 ucg node[619]:     at disconnect (/var/lib/node-red/node_modules/azure-iot-provisioning-device-mqtt/dist/mqtt.js:332:29)
Feb 04 13:33:28 ucg node[619]:     at Mqtt._disconnect (/var/lib/node-red/node_modules/azure-iot-provisioning-device-mqtt/dist/mqtt.js:353:13)
Feb 04 13:33:28 ucg node[619]:     at constructor._onEnter (/var/lib/node-red/node_modules/azure-iot-provisioning-device-mqtt/dist/mqtt.js:204:31)
Feb 04 13:33:28 ucg node[619]:     at constructor.transition (/var/lib/node-red/node_modules/machina/lib/webpack:/src/BehavioralFsm.js:175:1)
Feb 04 13:33:28 ucg node[619]:     at constructor.Fsm.(anonymous function) [as transition] (/var/lib/node-red/node_modules/machina/lib/webpack:/src/Fsm.js:80:1)
Feb 04 13:33:28 ucg node[619]:     at constructor.cancel (/var/lib/node-red/node_modules/azure-iot-provisioning-device-mqtt/dist/mqtt.js:164:36)
Feb 04 13:33:28 ucg node[619]:     at constructor.handle (/var/lib/node-red/node_modules/machina/lib/webpack:/src/BehavioralFsm.js:135:1)
Feb 04 13:33:28 ucg node[619]:     at constructor.Fsm.(anonymous function) [as handle] (/var/lib/node-red/node_modules/machina/lib/webpack:/src/Fsm.js:80:1)
Feb 04 13:33:28 ucg node[619]:     at Mqtt.cancel (/var/lib/node-red/node_modules/azure-iot-provisioning-device-mqtt/dist/mqtt.js:263:19)
Feb 04 13:33:28 ucg node[619]:     at constructor._onEnter (/var/lib/node-red/node_modules/azure-iot-provisioning-device/dist/polling_state_machine.js:223:42)
Feb 04 13:33:28 ucg node[619]:     at constructor.transition (/var/lib/node-red/node_modules/machina/lib/webpack:/src/BehavioralFsm.js:175:1)
Feb 04 13:33:28 ucg node[619]:     at constructor.Fsm.(anonymous function) [as transition] (/var/lib/node-red/node_modules/machina/lib/webpack:/src/Fsm.js:80:1)
Feb 04 13:33:28 ucg node[619]:     at constructor.cancel (/var/lib/node-red/node_modules/azure-iot-provisioning-device/dist/polling_state_machine.js:79:85)
Feb 04 13:33:28 ucg node[619]:     at constructor.handle (/var/lib/node-red/node_modules/machina/lib/webpack:/src/BehavioralFsm.js:135:1)
Feb 04 13:33:28 ucg node[619]:     at constructor.Fsm.(anonymous function) [as handle] (/var/lib/node-red/node_modules/machina/lib/webpack:/src/Fsm.js:80:1)
Feb 04 13:33:28 ucg node[619]:     at Timeout._onTimeout (/var/lib/node-red/node_modules/azure-iot-provisioning-device/dist/polling_state_machine.js:63:44)
Feb 04 13:33:28 ucg node[619]:     at ontimeout (timers.js:436:11)
Feb 04 13:33:28 ucg node[619]:     at tryOnTimeout (timers.js:300:5)
Feb 04 13:33:28 ucg node[619]:     at listOnTimeout (timers.js:263:5)
Feb 04 13:33:28 ucg node[619]:     at Timer.processTimers (timers.js:223:10)
Feb 04 13:33:28 ucg systemd[1]: uc-ui-node-red.service: Main process exited, code=exited, status=1/FAILURE
Feb 04 13:33:28 ucg systemd[1]: uc-ui-node-red.service: Failed with result 'exit-code'.
Feb 04 13:33:29 ucg systemd[1]: uc-ui-node-red.service: Service RestartSec=100ms expired, scheduling restart.
Feb 04 13:33:29 ucg systemd[1]: uc-ui-node-red.service: Scheduled restart job, restart counter is at 1.
Feb 04 13:33:29 ucg systemd[1]: Stopped Weidmueller u-control Node-Red.

Of course it is a completely wrong file and file format, but anyway, node-red should not crash... might be it is trying to parse the file but runs in an infinite loop since the expected content is not found in the file...

[DeviceForBugTest_1.cert.pfx.zip](https://github.com/iotblackbelt/node-red-contrib-azure-iot-device/files/5942778/DeviceForBugTest_1.cert.pfx.zip)

**Comment by iotblackbelt** [comment] 2021-02-15 15:24
Looks like this is an underlying SDK issue. I've created a bug for the issue on the [Node.js SDK](https://github.com/Azure/azure-iot-sdk-node/issues/931#issue-808625015).

**Comment by iotblackbelt** [comment] 2021-02-17 15:04
Issue is fixed with a work-around until SDK is fixed. Will e available in version 0.2.2

**Closed as completed by iotblackbelt** 2021-02-17 15:04 UTC
Labels: bug
